services:
  database:
    image: mysql:8.0
    container_name: photo-gallery-database
    restart: unless-stopped
    environment:
      # 这里仍需设置 Root 密码（这是 MySQL 镜像的要求）
      MYSQL_ROOT_PASSWORD: photo@zju
    volumes:
      - ./mysql/data:/var/lib/mysql
      # 核心：挂载初始化脚本目录
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    image: photo-gallery-backend:latest
    container_name: photo-gallery-backend
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5001 "app:create_app()"
    volumes:
      - ./backend/static/uploads:/app/static/uploads
    env_file:
      - .env
    ports:
      - "5001:5001"

  frontend:
    image: photo-gallery-frontend:latest # 直接使用刚才 load 进去的镜像名
    container_name: photo-gallery-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
